Fix: command import-grammars works now again
MaibornWolff/metric-gardener pull request #224
Opened 2024-03-14 16:18 UTC by ResistantBear

# Fix: command import-grammars works now again

Closes #223

## Description

`import-grammars` now works again after encapsulating the asynchronous import script into a lambda function, just like with the main `parse` command.

## Definition of Done

A PR is only ready for merge once all the following acceptance criteria are fulfilled:
* [x]  All TODOs related to this PR have been closed
* [ ]  There are automated tests for newly written code and bug fixes
* [x]  All bugs discovered while working on this PR have been submitted as issues (if not already an open issue)
* [x]  Documentation ([README.md](https://github.com/MaibornWolff/metric-gardener/blob/main/README.md), [UPDATE_GRAMMARS.md](https://github.com/MaibornWolff/metric-gardener/blob/main/UPDATE_GRAMMARS.md)) has been updated

2024-03-14 17:13 UTC, clemens-mw commented
can we write tests for this?

2024-03-14 17:15 UTC, clemens-mw requested changes
can we also add tests for this?

2024-03-15 07:19 UTC, clemens-mw commented on src/app.ts
> +        (argv) => {
or
```suggestion
        (_argv) => {
```

2024-03-15 07:57 UTC, ResistantBear commented
> can we also add tests for this?

For this fix? We would need to test our CLI for this. We do not have any tests for that yet. I propose to open a new issue for introducing such tests, also covering our other command `parse`. As without this change, the command `import-grammars` does not work at all and you will absolutely need this to support new languages like Perl, I propose to merge this immediately as a hotfix.

2024-03-15 08:00 UTC, ResistantBear commented
Concerning the import script itself, we do not have any tests for that currently, either.
We have issue #55 for this. As this command is only used by us as developers, we have not prioritized this.

2024-03-15 08:57 UTC, clemens-mw approved these changes
LGTM

2024-03-15 08:58 UTC, merged